# Generated by Django 3.1.7 on 2021-04-26 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210423_2044'),
        ('store', '0009_auto_20210424_1245'),
    ]

    operations = [
    ]
