# Generated by Django 3.2.6 on 2021-08-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_merge_20210426_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
